// Generated by CoffeeScript 2.5.1
(function() {
  // Dependencies
  var Card, app, createGame, deck, express, http, io, path, playerHand, server, shuffle, socketIO;

  express = require('express');

  http = require('http');

  path = require('path');

  socketIO = require('socket.io');

  app = express();

  server = http.Server(app);

  io = socketIO(server);

  app.set('port', 5000);

  app.use('/public', express.static(__dirname + '/static'));

  // Routing
  app.get('/', function(request, response) {
    response.sendFile(path.join(__dirname, 'index.html'));
  });

  // Starts the server.
  server.listen(5000, function() {
    console.log('Starting server on port 5000');
  });

  Card = class Card {
    constructor(color1, type) {
      this.color = color1;
      this.type = type;
      if (this.color === 'red' || this.color === 'green' || this.color === 'yellow' || this.color === 'blue') {
        this.id = this.color + "_" + this.type;
        this.name = this.color + " " + this.type;
      } else {
        this.id = this.type;
        this.name = this.type;
      }
    }

  };

  // Shuffle function
  shuffle = function(array) {
    var currentIndex, randomIndex, temporaryValue;
    currentIndex = array.length;
    temporaryValue = void 0;
    randomIndex = void 0;
    // While there remain elements to shuffle...
    while (0 !== currentIndex) {
      // Pick a remaining element...
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;
      // And swap it with the current element.
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }
    return array;
  };

  // Variables
  deck = [];

  playerHand = [];

  // Create Game
  createGame = function() {
    var createNewDeck, createPlayerHand;
    // Variables
    deck = [];
    playerHand = [];
    // Create new deck
    createNewDeck = function() {
      var cards, color, colors, count, i, j, len, len1, specials;
      deck = [];
      colors = ['red', 'green', 'yellow', 'blue'];
      specials = ['reverse', "reverse", 'skip', "skip", '+2', "+2"];
      for (i = 0, len = colors.length; i < len; i++) {
        color = colors[i];
        // Number Cards (with 0)
        count = 0;
        while (count <= 9) {
          deck.push(new Card(color, count));
          count++;
        }
        // Number Cards (without 0)
        count = 1;
        while (count <= 9) {
          deck.push(new Card(color, count));
          count++;
        }
// Color special cards
        for (j = 0, len1 = specials.length; j < len1; j++) {
          cards = specials[j];
          deck.push(new Card(color, cards));
          count++;
        }
      }
      // Wildcards
      count = 1;
      while (count <= 4) {
        deck.push(new Card(false, 'wildcard'));
        count++;
      }
      // +4 Cards
      count = 1;
      while (count <= 4) {
        deck.push(new Card(false, '+4'));
        count++;
      }
      shuffle(deck);
    };
    createPlayerHand = function() {
      playerHand = deck.slice(0, 7);
      deck = deck.slice(7);
    };
    createNewDeck();
    return createPlayerHand();
  };

  // Add the WebSocket handlerss
  io.on('connection', function(socket) {});

  /*
var players = {};
io.on('connection', function(socket) {
    socket.on('new player', function() {
        players[socket.id] = {
            x: 300,
            y: 300
        };
    });
    socket.on('movement', function(data) {
        var player = players[socket.id] || {};
        if (data.left) {
            player.x -= 5;
        }
        if (data.up) {
            player.y -= 5;
        }
        if (data.right) {
            player.x += 5;
        }
        if (data.down) {
            player.y += 5;
        }
    });
});

setInterval(function() {
    io.sockets.emit('state', players);
}, 1000 / 60);
*/

}).call(this);
